spring.application.name=pix-service

server.port=8081

pixserve.auth.username=admin
pixserve.auth.password=Test@123

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=50MB

#base.dir.path=F:\\pixserve_data
base.dir.path=/Users/arjunbhalekar/pix-serve-dev/storage

#---- MongoDB related ----
spring.data.mongodb.uri=mongodb://localhost:27017/pix-serve-dev
spring.data.mongodb.database=pix-serve-dev

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.security.*=DEBUG


bulk.upload.enabled=true
bulk.upload.src.dir.path=/Users/arjunbhalekar/pix-serve-dev/upload-bulk
bulk.upload.batch.size=20
bulk.upload.thread.pool.size=8
