server.port=8082

#---- AUTHENTICATION RELATED ----
pixserve.auth.username=${PIXSERVE_AUTH_USERNAME}
pixserve.auth.password=${PIXSERVE_AUTH_PASSWORD}

#---- IMAGE STORE BASE DIR PATH ----
base.dir.path=${BASE_DIR_PATH}

#---- MONGO DB RELATED ----
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}

#---- BULK UPLOAD RELATED ----
bulk.upload.enabled=${BULK_UPLOAD_ENABLED}
bulk.upload.src.dir.path=${BULK_UPLOAD_DIR_PATH}